### ISSUE TITLE
docs are out of date

### ISSUE THREAD

**Issue by ryuken** [feathersjs/feathers-primus#28]
Could this get updated docs?
Or is primus deprecated?
The docs here also are not consistent: https://docs.feathersjs.com/clients/primus.html

**Comment by daffl** [comment]
We haven't updated Primus to 6.0 yet (see #25). What exactly is outdated?

**Comment by ryuken** [comment]
I just got it working lol.
The docs are not clear on how to use it on the front-end.
There are 2 different ways listed on the link I posted above, but one doesn't even work.

I got it working like this:
```
import feathers from 'feathers/client';
import hooks from 'feathers-hooks';
import authentication from 'feathers-authentication/client';

import feathersPrimus from 'feathers-primus/client';
const primus = new Primus('/')

const app = feathers()
    .configure(hooks())
    .configure(feathersPrimus(primus))
    .configure(rx(RxJS))
    // Use localStorage to store our login token
    .configure(authentication({
        storage: window.localStorage
    }))
```

It's as simple as this but the docs aren't that clear lol

**Comment by daffl** [comment]
This is what is documented in the browser usage section at https://docs.feathersjs.com/clients/primus.html#browser-usage right?

That section should probably also include how to use it with a module loader.

**Comment by ryuken** [comment]
It says: ```.configure(feathers.primus(primus));```
feathers.primus doesn't even exist lol

I took this ```const primus = require('feathers-primus/client');``` from the server side usage on the same page and used that on client side lol, but I don't think that server side would need this client

**Comment by daffl** [comment]
It does exist and work if you are using the `feathers-client` as it is documented in the browser usage section (meaning including the script tags like `<script type="text/javascript" src="//unpkg.com/feathers-client@^1.0.0/dist/feathers.js"></script>`).

It does not if you are using it with a module loader like Webpack, Steal or Browserify. Then you have to do what you pointed out. What I was saying is to include that example for using a module loader in the browser usage section.

The server usage should still be correct. There is no reason why another Node server couldn't talk to an existing Feathers server but it requires more Primus setup work because the global `Primus` isn't available like it is in the browser.

**Comment by ekryski** [comment]
So what's the deal here? Are we going to add a module loader bit to the docs? Or are we all good and can now close this?

**Comment by leebenson** [comment]
I was confused too, but for another reason.

What threw me off is actually that `primus/primus.js` is automatically enabled as a route on the _server_ when configuring `feathers-primus`, and _that_ file needs to be included through a regular `<script>` tag before `new Primus()` is available on the client.

I had assumed `feathers-primus/client` would be all the client instantiation needed, and I could forego external `<script>` tags. Like @ryuken, I'm also using Webpack (in multiple places; via a `webpack-dev-server` and a production build served from a live web server, which changes how I'm able to pull in external scripts).

In my setup, the API server and the front-end are two distinct endpoints, so calling `primus/primus.js` actually needs to be done against my _other_ endpoint.

It might be useful to make it clear in the docs that `primus/primus.js` is automatically generated on the server, and it needs including _outside of webpack at the HTML level_ to instantiate properly.

**Comment by daffl** [comment]
This has been updated in the [latest Primus documentation](https://docs.feathersjs.com/api/primus.html). We can open new issues if some of the usage is still unclear.
