### ISSUE TITLE
Any breaking change in 2.0.0?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-primus#39]
I notice 2.0.0 is out here. Is there any API change? can we just simply upgrade to 2.0.0 from 1.x?

**Comment by daffl** [comment]
The breaking release was because of the update to Primus 6.0. I didn't have to change anything to upgrade but you can find the breaking Primus changes [in the Primus v6.0.0 tag](https://github.com/primus/primus/releases/tag/6.0.0)

**Comment by beeplin** [comment]
got it. thanks!
